blueprint:
  name: Flash Lights Blue if Rain is Forecasted for a Set Duration and Optional Time
  description: Flashes selected lights blue for a set duration when rain is forecasted, with an optional time window.
  domain: automation
  input:
    lights:
      name: Lights
      description: Lights to flash blue when rain is forecasted.
      selector:
        entity:
          domain: light
          multiple: true
    weather_entity:
      name: Weather Entity
      description: The weather entity to monitor for rain forecast.
      selector:
        entity:
          domain: weather
    flash_duration:
      name: Flash Duration (in seconds)
      description: Duration for which lights will flash blue.
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "seconds"
    start_time:
      name: Start Time (Optional)
      description: Optional start time for the automation to run.
      selector:
        time:
    end_time:
      name: End Time (Optional)
      description: Optional end time for the automation to run.
      selector:
        time:

trigger:
  platform: state
  entity_id: !input "weather_entity"

condition:
  - condition: template
    value_template: "{{ 'rain' in states(weather_entity) }}"
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ not start_time }}"
      - condition: time
        after: !input start_time
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ not end_time }}"
      - condition: time
        before: !input end_time

action:
  - service: light.turn_on
    data:
      entity_id: !input "lights"
      flash: short
      rgb_color: [0, 0, 255]

  - delay:
      seconds: !input flash_duration

  - service: light.turn_off
    data:
      entity_id: !input "lights"
